### ISSUE TITLE
Clients joining mid game break gamemode

### ISSUE THREAD

**Issue by kingofings** [rogeraabbccdd/CSGO-Super-Smash-Bros#4]
If clients or bots join mid game the gamemode breaks.
Also happens if a player joins Spectator and gets replaced by a newly joined client or bot.

Steps to reproduce (with bots):

Start round --> add bots mid round --> Gamemode breaks.

Video Demonstration:
https://youtu.be/DZaoqzPni-w

Error log:
[errors_20201214.log](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/files/5689995/errors_20201214.log)

System Info

Ubuntu 20.04.1 LTS
Sourcemod 1.10.0.6501
Metamod 1.11.0-dev+1143

**Comment by rogeraabbccdd** [comment]
This should be fixed.
