### ISSUE TITLE
LoadWeaponsConfig may break on mapchange + no sounds precached after error

### ISSUE THREAD

**Issue by kingofings** [rogeraabbccdd/CSGO-Super-Smash-Bros#5]
Sometimes when the map changes this error can occour and all of the sounds aren't prechached anymore.

Steps to reproduce:
Can happen on map change (only happened once so far)

Error log:
[errors_20201214.log](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/files/5691792/errors_20201214.log)

System Info:

Ubuntu 20.04.1 LTS
Sourcemod 1.10.0.6501
Metamod 1.11.0-dev+1143

**Comment by rogeraabbccdd** [comment]
Hi, can you post your weapon config file?

**Comment by rogeraabbccdd** [comment]
Just pushed an update, increased MAXWEAPONS to 100.
This is just a temporary workaround, CSGO don't have 100 weapons.

**Comment by kingofings** [comment]
Here you go 
[weapons.txt](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/files/5700901/weapons.txt)

(changed to txt github doesnt support .cfg)

**Comment by rogeraabbccdd** [comment]
Alright, the problem is sourcemod not reset some global variables after map change.
And there's a problem in your weapons.cfg, there's no `weapon_p2000`, it's `weapon_hkp2000`
