### ISSUE TITLE
Heavy Armor Model still visible after new round

### ISSUE THREAD

**Issue by kingofings** [rogeraabbccdd/CSGO-Super-Smash-Bros#6]
The Heavy armor Model will still be visible in the next round if the player didn't die.

The Armor and it's effects are gone though for other players it can be quite misleading.

Ubuntu 20.04.1 LTS
Sourcemod 1.10.0.6501
Metamod 1.11.0-dev+1143

**Comment by rogeraabbccdd** [comment]
This seems to be CSGO items plugin problem, you should create issue at https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros-CSGOWeapons
