### ISSUE TITLE
OnMapStart Error Array index out of bounds

### ISSUE THREAD

**Issue by kingofings** [rogeraabbccdd/CSGO-Super-Smash-Bros#8]
This issue seems to be related to #5. Same things happen. After mapchange error can occour + no more sound precached.

It seems the weapon counts doesn't get reset sometimes even with your latest fix. This however did not cause an error from LoadWeaponsconfig. The Errorlog (linked below) only showed an issue with OnMapStart.

[errors_20201221.log](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/files/5721724/errors_20201221.log)
Weapon Config:

[weapons.txt](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/files/5721727/weapons.txt)

System Info

Ubuntu 20.04.1 LTS
Sourcemod 1.10.0.6501
Metamod 1.11.0-dev+1143

**Comment by rogeraabbccdd** [comment]
Map trigger_hurt count is not reset.
It seems like I have to reset everything on map start.
https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/blob/e5b26a753203abe6add411103f8bfbd43e7b7d2c/scripting/kento_smashbros.sp#L227-L235
